### ISSUE TITLE
"Prefer: plurality=singular" does not work with /rpc

### ISSUE THREAD

**Issue by tnhu** [begriffs/postgrest#776]
I found that setting header "Prefer: plurality=singular" actually not working for /rpc call.

```sql
CREATE FUNCTION rpc_test() RETURNS text[]
AS $$
	select ARRAY['one', 'two', 'three'];
$$ LANGUAGE sql;
```

```sh
curl -X POST -H "Content-Type: application/json" -H "Prefer: plurality=singular" -d '{}' "http://localhost:3333/rpc/rpc_test"
```

```json
[
    {
        "rpc_test": [
            "one",
            "two",
            "three"
        ]
    }
]
```

**Expected**:

```json
{
    "rpc_test": [
        "one",
        "two",
        "three"
    ]
}
```

**Comment by ruslantalpa** [comment]
Is this in 3.2 or master
I think in master you would have gotten
```
[ "one","two","three"]
```
without the prefer header

**Comment by tnhu** [comment]
@ruslantalpa I'm in 0.3.2.0/Mac El Capitan (installed from brew). Will try to build from source/master to see how it goes.

**Comment by begriffs** [comment]
FYI, the docs for this unreleased version are at https://postgrest.readthedocs.io/en/v0.4/

They have updated instructions for running the server etc.

**Comment by tnhu** [comment]
@begriffs Thanks for the info. It was not straightforward to build from source (under MacOS, and I'm not familiar with Haskell). The following instruction did not work right away.

```
git clone https://github.com/begriffs/postgrest.git
cd postgrest
stack build --install-ghc
sudo stack install --allow-different-user --local-bin-path /usr/local/bin
```

Couple of issues:

```stack build --install-ghc```

***Error***: `dyld: Library not loaded`, fixed by `brew install gmp`

```sudo stack install --allow-different-user --local-bin-path /usr/local/bin```

***Error***: ```Executable named nix-shell not found on path:```, fixed by ```curl https://nixos.org/nix/install | sh```

*Run it again:*

```sudo stack install --allow-different-user --local-bin-path /usr/local/bin```

***Error***: ```warning: the group ‘nixbld’ specified in ‘build-users-group’ does not exist
error: file ‘nixpkgs’ was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:14```

I ended up just doing:

```
stack install
```

to make `stack` install postgrest into `~/.local/bin`. Yayyy, at least it's working now :)

**Comment by begriffs** [comment]
Thanks for letting me know about the install difficulties. Not sure why it wants nix, that's weird. But I'll look into this in the next few days and improve the docs.

**Comment by begriffs** [comment]
I incorporated your suggestions into the docs. Thanks again for real!

**Comment by begriffs** [comment]
About the original question: version 0.4 is now released and supports singular responses for RPC. Thew new way to do this does not involve the Prefer header. Instead request with the `Accept: application/vnd.pgrst.object+json` header (the `+json` is optional). Let me know if this works for you.

**Comment by uniphil** [comment]
Then the [0.4 docs are out of date](http://postgrest.com/en/v0.4/api.html#singular-or-plural); they still specify the `Prefer: plurality=singular` header, so I think this issue is still not resolved, or maybe another should be opened for the bad docs?
